local datos = require("main.datos")
local remedios = require("game.game gui.glosario.remedios")

-- Vars funciones
local crear_bicho;
function init(self)
	--timer.delay(1, false, crear_bicho)
	crear_bicho();
end

function final(self)

end

function on_message(self, message_id, message, sender)

end

function on_input(self, action_id, action)

end

crear_bicho = function()
	factory.create("#bicho_fac", nil, nil, {estado = 2})
end











